name: Create new release

on:
  workflow_dispatch:
    inputs:
      restateVersion:
        description: "Restate version"
        required: true
        type: string

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Verify Restate release exists
        uses: cardinalby/git-get-release-action@v1
        id: restate-release
        env:
            GITHUB_TOKEN: ${{ secrets.REPO_READ_ACCESS }}
        with:
          repo: restatedev/restate
          draft: false
          prerelease: false
          tag: ${{ inputs.restateVersion }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Dockerfile to point to new release
        run: |
          release_tag=${{ inputs.restateVersion }}
          if [[ ${release_tag} = v* ]]; then
            # remove v character
            release_tag="${release_tag:1}"
          fi
          sed -i "s/FROM ghcr.io\/restatedev\/restate:.*$/FROM ghcr.io\/restatedev\/restate:${release_tag}/g" docker/Dockerfile
          cat docker/Dockerfile

      - name: Commit updated Dockerfile and tag release
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          tag: ${{ inputs.restateVersion }}
          message: Restate distribution release ${{ inputs.restateVersion }}
          add: ./docker/Dockerfile
