name: Create new release

on:
  push:
    tags:
      - v**

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Fetch release artifacts from ${{ github.ref_name }}
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "restatedev/restate"
          tag: "${{ github.ref_name }}"
          fileName: "restate-cli-*.zip"
          token: ${{ secrets.REPO_READ_ACCESS }}

      - name: List artifacts
        id: list-artifacts
        run: |
          # check whether we have fetched some artifacts
          if ls restate-cli-*.zip >/dev/null 2>&1; then
            echo "ARTIFACTS<<EOF" >> $GITHUB_OUTPUT
            ls -1 restate-cli-*.zip >> $GITHUB_OUTPUT || true
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          # create a draft release which needs manual approval
          draft: true
          files: ${{ steps.list-artifacts.outputs.ARTIFACTS }}
